name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_ios:
    name: Test iOS framework
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Force Xcode 11.4
        run: sudo xcode-select -switch /Applications/Xcode_11.4_beta.app
      - name: Test SPM
        run: |
          swift test --parallel
          swift build -c debug
          swift build -c release
      - name: Test project - iOS framework
        run: |
          xcodebuild clean test -project PACTSwift.xcodeproj -scheme pact-swift -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty
  test_macOS:
    name: Test macOS framework
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Force Xcode 11.4
        run: sudo xcode-select -switch /Applications/Xcode_11.4_beta.app
      - name: Test SPM
        run: |
          swift test --parallel
          swift build -c debug
          swift build -c release
      - name: Test project - macOS framework
        run: |
          xcodebuild clean test -project PACTSwift.xcodeproj -scheme pact-swift -destination "platform=macOS" | xcpretty
